### PR TITLE
add images browser

### PR DESCRIPTION
**Pull request by fa0311**
### 概要
- 過去に作成した画像を閲覧する機能を追加しました
image
- pngのメタデータが保存されていなかった問題を修正しました
- Galleryのimg2imgが空っぽなバグを修正しました
- 少しリファクタリングしました

### 課題
~infoが空っぽなので外部に保存するか他のWebUIのように画像にメタデータとして保存する必要がある~<https://github.com/ddPn08/Lsmith/compare/main...fa0311:Lsmith:add-gallery?expand=1#diff-c4527fee4f6fa4dfdf25ffbe014e44632a928857f9ae4b93e68dd395f30d2ab9R18-R20>
この機能を実装した #44 をマージしました

### Overview
- Added the ability to view images created in the past
image
- Fixed an issue where png metadata was not being saved
- Fixed a bug that img2img in Gallery was empty
- Some refactoring

### Future issues
~info is empty, so it needs to be stored externally or as metadata in an image like other WebUI~
<https://github.com/ddPn08/Lsmith/compare/main...fa0311:Lsmith:add-gallery?expand=1#diff-c4527fee4f6fa4dfdf25ffbe014e44632a928857f9ae4b93e68dd395f30d2ab9R18-R20>
Merged #44 which implements this feature

### CODE REVIEW

**Comment by fa0311** [comment]
下の方見切れてるのでそこを直す

**Comment by Stax124** [comment]
@fa0311 Would you please use English in PRs, its really painful to follow as a non-japanese user.

**Comment by fa0311** [comment]
> Would you please use English in PRs, its really painful to follow as a non-japanese user.

I have updated the comments.
Since the maintainer is Japanese, we used to use Japanese, but now we will use both.

**Comment by Stax124** [comment]
Thank you very much.

On the topic of image browsers, I have created metadata writer for Volta, would you be interested in integrating it in UI if I make a PR for the backend?

**Comment by fa0311** [comment]
> On the topic of image browsers, I have created metadata writer for Volta, would you be interested in integrating it in UI if I make a PR for the backend?

It is possible, but I am already working on it.

**Comment by Stax124** [comment]
Ok, then I will leave it to you, feel free to take some code from https://github.com/VoltaML/voltaML-fast-stable-diffusion/blob/a12bd8c6cbff3d73e62fe659666ecb59f69ca466/core/png_metadata.py

**Comment by fa0311** [comment]
Added info preview.
image

**Comment by fa0311** [comment]
image
Parameters by other WebUI

**Comment by ddPn08** [comment]
めっちゃ助かります！ありがとうございます；

---

Thank you very much.

**Review by ddPn08 — APPROVED** [review]

**Pull request merged**
