### PR TITLE
Create Vitepress documentation, workflows, issue templates for GitHub, Black pre-commit hook

### PR DESCRIPTION
**Pull request by Stax124**
**Docs**
- stored in `docs/`
- written in Markdown (easy to use)
- simple to use Wiki

 **Workflows**
- CodeQL scanning - checks for code issues (Python and TypeScript)
- Black (fails on improperly formatted code)
- Documentation (auto-build on push to `main` branch)

 **Issue Templates**
- Example [here](https://github.com/Stax124/MoltenCore/issues/new/choose)
- Easy way for users to fill out a form with a better understanding of nice to have information to submit

**Pre-commit hook**
- runs when the user commits locally
- will be installed with `requirements.txt`
- configured to run `Black` formatter on the codebase

**Reformatted gitignore and readme.md**
- Better readability

### CODE REVIEW

**Comment by Stax124** [comment]
**Needs to be enabled for the documentation to work (both can be found on the `Settings` page)**

---

image

---

image

**Comment by Stax124** [comment]
**Test page deployed to**: https://stax124.github.io/Lsmith/

**Comment by ddPn08** [comment]
Thank you for your wonderful PR.
Do I have to create the branch "gh-pages" myself?

**Comment by Stax124** [comment]
> Thank you for your wonderful PR. Do I have to create the branch "gh-pages" myself?

It will be created on the first run by the CI pipeline, no worries.

**Comment by ddPn08** [comment]
I got it. Is it okay to merge this already?

**Comment by Stax124** [comment]
Yup, ready

**Review by ddPn08 — APPROVED** [review]

**Pull request merged**
